import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { cn } from "~/lib/utils";
import { ThemeProvider } from "~/components/theme";

import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout(props: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={cn(GeistSans.variable, GeistMono.variable, "antialiased")}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {props.children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
